name: Updater
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate Hashes and Links
        run: |
          cd $GITHUB_WORKSPACE
          find libraries/ -type f -exec sha1sum {} + | awk '{print $2 ":" $1}' > library_hashes.txt
          find natives/ -type f -exec sha1sum {} + | awk '{print $2 ":" $1}' > native_hashes.txt
          find libraries/ -type f -exec sh -c 'filename=${1#./}; echo "https://github.com/Modern-Developers/ModernGuard-Natives/raw/main/$filename"' _ {} \; > libraries2.txt
          find natives/ -type f -exec sh -c 'filename=${1#./}; echo "https://github.com/Modern-Developers/ModernGuard-Natives/raw/main/$filename"' _ {} \; > natives.txt

      - name: Commit and Push Changes
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "siroo2137"
          git config user.email "dawideqgamesonline@gmail.com"
          git add --all
          git commit --allow-empty -m "[Updater] Updating hashes and links."
          git push
