name: Updater
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate Hashes
        run: |
          cd $GITHUB_WORKSPACE
          find . -type f -exec sha256sum {} + | awk '{print $2 ":" $1}' > hashes2.txt

      - name: Get list of file names
        id: get_filenames
        run: |
          cd $GITHUB_WORKSPACE
          find . -type f -exec sh -c 'filename=$(echo "{}" | sed "s/^\.\///"); echo "https://github.com/Modern-Developers/ModernGuard-Natives/raw/main/libraries/${filename}" >> libraries2.txt' \;

      - name: Commit and Push Changes
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "siroo2137"
          git config user.email "dawideqgamesonline@gmail.com"
          git add --all
          git commit --allow-empty -m "[Updater] Updating hashes and links."
          git push
