name: Updater
on:
  push:
    branches:
      - main

jobs:
  update_hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate Hashes
        run: |
          cd $GITHUB_WORKSPACE
          find . -type f -exec sha256sum {} + > hashes2.txt
          awk '{print "- " $1 "  " $2}' hashes2.txt > hashes.txt

      - name: Get list of file names
        id: get_filenames
        run: |
          cd $GITHUB_WORKSPACE
          find . -type f -exec sh -c 'echo "https://github.com/Modern-Developers/ModernGuard-Natives/raw/main/libraries/{}" >> libraries2.txt' \;

      - name: Set Git identity
        run: |
          git config user.name "siroo2137"
          git config user.email "dawideqgamesonline@gmail.com"

      - name: Commit and Push Changes
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE
          git add --all
          git commit --allow-empty -m "[Updater] Updating hashes and links."
          git push origin main
          # Use the token for authentication during push
          git push https://github.com/Modern-Developers/ModernGuard-Natives.git HEAD:main
